# Generated by Django 5.2.17 on 2026-08-05 18:20

import crm.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('mail_sub', models.CharField(help_text='Supports {{ variable }} placeholders.', max_length=300)),
                ('mail_body', models.TextField(help_text='Supports {{ variable }} placeholders.')),
                ('var_list', models.JSONField(blank=True, default=list, help_text='Declared variables, e.g. ["first_name", "company", "designation"].')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(help_text='Unique -- this is the dedupe key for CSV import.', max_length=254, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number (no +91, no spaces).', regex='^[6-9]\\d{9}$')])),
                ('linkedin', models.URLField(blank=True)),
                ('company', models.CharField(db_index=True, max_length=160)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['company', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('bits_email', models.EmailField(help_text='Must match the Gmail account used by the local sending agent.', max_length=254, unique=True, validators=[crm.validators.validate_bits_email])),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number (no +91, no spaces).', regex='^[6-9]\\d{9}$')])),
                ('linkedin', models.URLField(blank=True)),
                ('batch', models.CharField(db_index=True, help_text='Admission year. Drives permissions -- see services/permissions.py.', max_length=4, validators=[django.core.validators.RegexValidator(message='Batch must be a 4-digit year like 2024.', regex='^20\\d{2}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.contact')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.teammember')),
            ],
            options={
                'db_table': 'contact_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to='crm.teammember'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_contacted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.teammember'),
        ),
        migrations.CreateModel(
            name='CampaignMailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mail_thread_id', models.CharField(blank=True, max_length=120)),
                ('mail_message_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=8)),
                ('rendered_subject', models.TextField(blank=True)),
                ('rendered_body', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailings', to='crm.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailings', to='crm.contact')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailings', to='crm.teammember')),
            ],
            options={
                'db_table': 'campaign_mailings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='crm.teammember'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['assigned_to', 'company'], name='contacts_assigne_7c7df6_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmailing',
            index=models.Index(fields=['campaign', 'status'], name='campaign_ma_campaig_5f3457_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmailing',
            index=models.Index(fields=['sent_by', 'sent_at'], name='campaign_ma_sent_by_95fae5_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignmailing',
            constraint=models.UniqueConstraint(fields=('campaign', 'contact'), name='uniq_campaign_contact'),
        ),
    ]
