# Generated by Django 5.2.17 on 2026-08-05 19:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text="e.g. 'Aarav's MacBook'", max_length=80)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First chars, shown in the UI.', max_length=8)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='crm.teammember')),
            ],
            options={
                'db_table': 'api_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
