# Generated by Django 5.2.17 on 2026-08-08 11:18

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=40)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'contact_audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.teammember'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.teammember'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='lifecycle',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('bounced', 'Bounced'), ('do_not_contact', 'Do Not Contact')], db_index=True, default='new', help_text="Flips to 'contacted' automatically on the first sent mail.", max_length=16),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='Free-form labels, e.g. fintech, priority, iit-b.', size=None),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_archived', 'lifecycle'], name='contacts_is_arch_31069b_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='contacts_tags_gin'),
        ),
        migrations.AddField(
            model_name='contactaudit',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.teammember'),
        ),
        migrations.AddField(
            model_name='contactaudit',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='crm.contact'),
        ),
        migrations.AddIndex(
            model_name='contactaudit',
            index=models.Index(fields=['contact', '-created_at'], name='contact_aud_contact_7585a1_idx'),
        ),
    ]
