# Generated by Django 5.2.17 on 2026-08-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_contact_lifecycle_tags_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmailing',
            name='rendered_body_html',
            field=models.TextField(blank=True),
        ),
    ]
