# Generated by Django 5.2.17 on 2026-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_campaign_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_html',
            field=models.BooleanField(default=False, help_text='Write raw HTML in the body -- footers, styling, dividers.'),
        ),
        migrations.AddField(
            model_name='campaignmailing',
            name='bcc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='campaignmailing',
            name='cc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='campaignmailing',
            name='from_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='teammember',
            name='sender_name',
            field=models.CharField(blank=True, help_text="Shown as the sender in the recipient's inbox. Blank uses the member's name. A bare address in a cold mail is far less likely to be opened.", max_length=120),
        ),
    ]
