# Generated by Django 5.2.17 on 2026-08-18 15:24

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_sender_name_cc_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('held', 'Held'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('cc', models.CharField(blank=True, max_length=500)),
                ('bcc', models.CharField(blank=True, max_length=500)),
                ('leased_by', models.CharField(blank=True, max_length=80)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='crm.campaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.teammember')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='crm.teammember')),
            ],
            options={
                'db_table': 'scheduled_sends',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='scheduled_s_status_15a9a2_idx'), models.Index(fields=['member', 'status'], name='scheduled_s_member__3b58e3_idx')],
            },
        ),
    ]
