# Generated by Django 5.2.17 on 2026-08-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_scheduled_sends'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledsend',
            name='batch_size',
            field=models.PositiveIntegerField(default=0, help_text='Contacts per run. 0 sends the whole selection at once.'),
        ),
        migrations.AddField(
            model_name='scheduledsend',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Wait between batches. Ignored unless batch_size is set.'),
        ),
        migrations.AddField(
            model_name='scheduledsend',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
