# Generated by Django 5.2.17 on 2026-08-18 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_schedule_drip'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmailing',
            name='followed_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignmailing',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignmailing',
            name='reply_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FollowUpRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delay_days', models.PositiveIntegerField(default=3, help_text='Days of silence before the follow-up is queued.')),
                ('is_active', models.BooleanField(default=True)),
                ('mark_replied', models.BooleanField(default=False, help_text="Also set the contact's lifecycle to Replied when a reply is seen.")),
                ('campaign', models.ForeignKey(help_text='The campaign whose silence we are following up on.', on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_rules', to='crm.campaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.teammember')),
                ('follow_up', models.ForeignKey(help_text='What to send them instead.', on_delete=django.db.models.deletion.PROTECT, related_name='follows_from', to='crm.campaign')),
            ],
            options={
                'db_table': 'follow_up_rules',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'follow_up'), name='uniq_followup_pair')],
            },
        ),
    ]
